### ISSUE TITLE
Useful book to get to generate the MCQ?

### ISSUE THREAD

**Issue by kgashok** [kgashok/orientations#26]
Maybe there is a PDF somewhere? 
Is this book available in the library?

![Screenshot 2016-11-17 at 23.21.01.png](https://zube.io/files/kgashok/fb97b3de195c5b54c226cdcccaf91d6e.png)

**Comment by Dhivyakgisl** [comment]
Dear sir, 
  
     I would prefer using Headfirst Java book. I have the PDF copy for the same. 
  
With regards, 
Dhivya 

----- Original Message -----

**Comment by Dhivyakgisl** [comment]
Headfirst JAVA PDF copy
https://drive.google.com/file/d/0B8gMR6tSBoZsNDNkMjZjOGItYjljYS00OTFhLTg1ZTgtMzRhNTMxZjcxMjJj/view?hl=en
 @kgashok @62ramya @aBharathy

**Comment by 62ramya** [comment]
Sir, The book is available in KITE Library.

**Comment by kgashok** [comment]
The Java FAQ book?

Ashok Bakthavathsalam

**Comment by 62ramya** [comment]
Yes, sir.
