### ISSUE TITLE
Import Current Java manual into the repo

### ISSUE THREAD

**Issue by kgashok** [kgashok/orientations#3]

**Comment by kgashok** [comment]
@Dhivyakgisl  

https://github.com/kgashok/orientations/blob/master/javaLab/LAB_Exercises.md - the lab solution keys can be proof read for naming conventions, indentations, etc.
Assign all or SOME of the lab exercises to the 18+ KGISL freshers and ask them to contribute to the improved lab manuals.

They have to get a bit familiar with the Markdown format (stackedit.io is a good editor to use).

**Comment by Dhivyakgisl** [comment]
Dear sir, 
  
    Will allocate all programs to 18 trainees and do the needful. 
  
With regards, 
Dhivya 

----- Original Message -----

**Comment by kgashok** [comment]
@Dhivyakgisl @nandini-haricharan - is the Java Manual ready for review?

**Comment by Dhivyakgisl** [comment]
Sir, will load by day end. 

----- Original Message -----

**Comment by nandini-haricharan** [comment]
It is ready.
Had to refine a bit. It's done. Will review and upload by noon Dhivya and Sir.

**Comment by nandini-haricharan** [comment]
[Java Lab Exercises with Solutions.docx](https://github.com/kgashok/orientations/files/656531/Java.Lab.Exercises.with.Solutions.docx)

**Comment by kgashok** [comment]
Please change indent spaces to 4.

  % ashok

**Comment by nandini-haricharan** [comment]
Uploading the word & pdf formats of Java Manual :
[Java Lab Manual.docx](https://github.com/kgashok/orientations/files/657170/Java.Lab.Manual.docx)
[Java Lab Manual.pdf](https://github.com/kgashok/orientations/files/657171/Java.Lab.Manual.pdf)

**Comment by kgashok** [comment]
@nandini-haricharan  I reviewed PDF version, and I found these: 

1. Inconsistent indent spacing (Look at Lab #3) across the manual 
2. Bad indentation (comments are not _inline_ with the **import** statements in Lab #3)
3. Wrapping around is happening making the code not readable. Let's consistently use indent spacing at 2. 
4. Can we put some header/footer and indicating copyright @KGCAS and/or KGISL?

Please fix.

**Comment by nandini-haricharan** [comment]
Sir,

I will mail you the .doc and .pdf versions after the below changes before we can post them here. 

1. Changed the line spacing to 1.5 across the document.
2. Change has been made to keep the comment and import statements in line for all the questions.
3_. The indent spacing has been kept to 2 based on your feedback earlier. Yet there are bound to be lines (long ones) which will reflect word wrap when we put them in Word. I have tried to decrease the font size as well.
5. Yes, we can. I will do the same.

**Comment by kgashok** [comment]
@nandini-haricharan 

https://github.com/kgashok/orientations/tree/master/JavaLab%20using%20C9 
is the folder for dumping all the individual lab exercises. 

The PDF and Word manuals can be placed at the top level.

**Comment by nandini-haricharan** [comment]
Sir, I am not able to create FOLDERS. does it require any access? I have uploaded the java files.

**Comment by kgashok** [comment]
@nandini-haricharan Files now in the same directory. We will consider separate folders later. 
@sathyavathyvenugopal Please review the files and call me.

**Comment by sathyavathyvenugopal** [comment]
Respected Sir,
             I will review the files and call to you sir.
