### ISSUE TITLE
Invite Sathyavathy as a collaborator on the repo

### ISSUE THREAD

**Issue by kgashok** [kgashok/orientations#4]

**Comment by aBharathy** [comment]
@sathyavathyvenugopal is the Id of Ms. Sathyavahy

**Comment by kgashok** [comment]
I've invited her. She's yet to join.

Ashok Bakthavathsalam

**Comment by kgashok** [comment]
@aBharathy Can you please upload the JAVA LAB MANUAL to this repo? Collect it from whomever it is with.

**Comment by aBharathy** [comment]
Yes sir. Working on it . As soon as  I receive it , will upload
