### ISSUE TITLE
Create PetSpeak exercise series in Java

### ISSUE THREAD

**Issue by kgashok** [kgashok/orientations#9]
Rajasekaran (KITE) has been assigned this work.

**Comment by kgashok** [comment]
@rajasekaranap - please respond with deadlines.

**Comment by rajasekaran36** [comment]
Sure sir ...

**Comment by kgashok** [comment]
https://github.com/rajasekaranap/Pet-Talk-Abstract-Java/tree/master/src

I've done a couple of pull requests on your repo. Once that's accepted, it will have three very different versions, which should all work.
